version: 2

sources:
  - name: erp_adventure_works
    description: Fonte do sistema ERP da empresa Adventure Works,incluindo os dados de fabricação, vendas, compras, gerenciamento de produtos, gestão de contatos e recursos humanos.
    database: FEA24_9
    schema: RAW_ADVENTURE_WORKS
    tables:
      - name: PRODUCT
        description: 'Tabela com dados gerais sobre os produtos fabricados e vendidos pela adventure works'
        columns:
          - name: PRODUCTID
            tests:
              - not_null
              - unique  
      - name: PRODUCTCATEGORY
        description: 'Tabela que classifica os produtos em categorias'
        columns:
          - name: PRODUCTCATEGORYID
            tests:
              - not_null
              - unique  
      - name: PRODUCTSUBCATEGORY
        description: 'Tabela que classifica os produtos em subcategorias'
        columns:
          - name: PRODUCTSUBCATEGORYID
            tests:
              - not_null
              - unique  
      - name: CUSTOMER
        description: 'Tabela com dados sobre os clientes da empresa'
        columns: 
          - name: CUSTOMERID
            tests:
              - not_null
              - unique  
      - name: CREDITCARD
        description: 'Tabela que contém os detalhes dos cartões de crédito dos clientes'
        columns:
          - name: CREDITCARDID
            tests:
              - not_null
              - unique  
      - name: PERSONCREDITCARD
        description: 'Tabela de referência cruzada, mapeando pessoas com informações de cartão de crédito na tabela CreditCard'
        columns:
          - name: BUSINESSENTITYID
            tests:
              - not_null
              - unique          
      - name: PERSON
        description: 'Tabela com informaçãoes das pessoas envolvidas com a adventure works (clientes, funcionários e fornecedores)'
        columns:
          - name: BUSINESSENTITYID
            tests:
              - not_null
              - unique  
      - name: ADDRESS
        description: 'Tabela com informações de endereço de clientes, funcionários e fornecedores'
        columns:
          - name: ADDRESSID
            tests:
              - not_null
              - unique                
      - name: COUNTRYREGION
        description: 'Tabela com informações sobre regiões e países'
        columns:
          - name: COUNTRYREGIONCODE
            tests:
              - not_null
              - unique          
      - name: STATEPROVINCE
        description: 'Tabela com dados sobre estados e províncias'
        columns:
          - name: STATEPROVINCEID
            tests:
              - not_null
              - unique  
          - name: STATEPROVINCECODE
            tests:
              - not_null
      - name: SALESORDERDETAIL
        description: 'Tabela com dados detalhados dos produtos associados a um pedido de venda específico'
        columns:
          - name: SALESORDERDETAILID
            tests:
              - not_null
              - unique  
          - name: SALESORDERID
            tests:
              - not_null
      - name: SALESORDERHEADER
        description: 'Tabela com informações gerais sobre pedidos de vendas'
        columns:
          - name: SALESORDERID
            tests:
              - not_null
              - unique  
          - name: CUSTOMERID
            tests:
              - not_null
      - name: SALESORDERHEADERSALESREASON
        description: 'Tabela que relaciona os pedidos(salesorderid) de venda e seus motivos/razões '
        columns:
          - name: SalesReasonID
            tests:
              - not_null              
          - name: SalesOrderID
            tests:
              - not_null
      - name: SALESPERSON
        description: 'Tabela com dados sobre os vendedores da adventure works'
        columns:
          - name: BUSINESSENTITYID
            tests:
              - not_null
              - unique 
      - name: SALESREASON
        description: 'Tabela com dados dos motivos/razões de compras pelos clientes'
        columns:
          - name: SALESREASONID
            tests:
              - not_null
              - unique  
      - name: STORE
        description: 'Tabela com informações sobre cadastros das lojas/ clientes (revendedores) de produtos Adventure Works'
        columns:
          - name: BUSINESSENTITYID
            tests:
              - not_null
              - unique  

      - name: SHIPMETHOD
        description: 'Tabela com informações dos métodos de envio disponíveis'
        columns:
          - name: SHIPMETHODID
            tests:
              - not_null
              - unique  
          
